/rm_decision_node:
  ros__parameters:
    route1: [0.0, 0.0, 0.0,
              0.0, 3.0, 0.0]
    route2: [1.0, 1.0, 2.0,
                  3.0, 4.0, 5.0,
                  6.0, 7.0, 8.0]
    home_pose: [0.0, 0.0, 0.0]
